# Generated by Django 3.1.8 on 2022-02-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000, verbose_name='文本')),
                ('type', models.CharField(default='123', max_length=50, verbose_name='类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('owner', models.CharField(default='', max_length=50, verbose_name='角色')),
            ],
            options={
                'db_table': 'text',
            },
        ),
    ]
